version: '3.8'
services:
  deletebot:
    container_name: deletebot
    build:
      context: .
      dockerfile: ./docker/Dockerfile.deletebot
    environment:
      - TOKEN=${TOKEN}
      - DBLTOKEN=${DBLTOKEN}
    network_mode: 'bridge'
    healthcheck:
      test: ["CMD", "curl", "--fail", "-s", "-o", "/dev/null", "https://discord.com/api/v8"]
      interval: 60s
      timeout: 5s
      retries: 3
